name: check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: template
        run: |
          git config --global init.defaultBranch main

          mkdir example-project
          cd example-project

          nix flake init -t ..#default

          git init
          git add -A

          # Override the nixpkgs input of the template to use the current branch,
          # since that is the branch of interest we want to test
          nix flake lock --override-input lighthouse-flake "github:marijanp/lighthouse-flake/$GITHUB_REF"

          nix flake check -L

